spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    mongodb:
      host: anilspersonalpagescosmosdb.mongo.cosmos.azure.com
      uri: mongodb://anilspersonalpagescosmosdb:GrvOA8AewXAeawOtaUZfIR9oCeiFqpOwcMdBJ8N7SO1u79ftDZFGHouMtRjgH0nX2cKRmcaxW8p5ACDb8tCBsw==@anilspersonalpagescosmosdb.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@anilspersonalpagescosmosdb@
      database: mydb
