apiVersion: v1
kind: Pod
metadata:
  name: personalpagepod
  namespace: nspersonalpage
spec:
  containers:
    - name: personalpage
      image: mybandscontainerregistry.azurecr.io/personalpage:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"