apiVersion: v1
kind: ReplicationController
metadata:
  name: rcpersonalpage
  namespace: nspersonalpage
spec:
  replicas: 2
  selector:
    rc-name: my-rc
  template:                                   # pod definition starts from here
    metadata:
      name: personalpagepod
      labels:
        rc-name: my-rc
        app: my-label-1
    spec:
      containers:
      - name: container
        image: mybandscontainerregistry.azurecr.io/personalpage:latest
        ports:
        - containerPort: 8080